language: python
python:
   - 2.7
   - 3.2
   - 3.3
install:
   - pip install nose coverage
script:
  - nosetests --with-coverage --cover-package=depsolver --cover-inclusive depsolver
notifications:
  email:
    - davidc@enthought.com
